### PR TITLE
Conor/new look duck

### PR DESCRIPTION
**Pull request by c-brenn**
The email spec pass but have not tested it by sending an actual email :pray:

### CODE REVIEW

**Comment by c-brenn** [comment]
I should add, all the services pictures work a lot better when they are the facebook banner aspect ratio. Also uploading the event images in a higher resolution would make the highlighted event part look nicer

**Comment by PinPinIre** [comment]
Any progress on this?

**Comment by CalvinNolan** [comment]
Yeah it'll be deployed before we get back to college

**Comment by CalvinNolan** [comment]
r i p

**Pull request closed without merging**
